import Head from "next/head";
import { resetServerContext } from "react-beautiful-dnd";
import Todos from "../components/Todos";

export default function Home() {
  return (
    <div className="h-screen w-screen overflow-x-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-full h-[45%] flex justify-center">
        <div className="bg-light-image dark:bg-dark-image bg-cover w-full h-full" />
        <Todos />
      </div>
    </div>
  );
}

{
  /* for drag and drop component */
}
export async function getServerSideProps({ query }) {
  resetServerContext();

  return { props: { data: [] } };
}
